services:
- hash: e92c2b2bf9fcbd30be19c692e4cc858ef34ec193
  name: prometheus-telemeter-cache
  path: /prometheus-telemeter-cache.yaml
  url: https://github.com/app-sre/saas-telemeter-cache-manifests
  environments:
  - name: production
    parameters:
      APPNAME: telemeter-cache
      NAMESPACE: telemeter-cache-production
      SERVICEMONITOR_TARGET_NAMESPACE: telemeter-production
      SERVICEMONITOR_TARGET_SERVERNAME: prometheus-telemeter.telemeter-production.svc
  - name: staging
    parameters:
      APPNAME: telemeter-cache
      NAMESPACE: telemeter-cache-stage
      SERVICEMONITOR_TARGET_NAMESPACE: telemeter-stage
      SERVICEMONITOR_TARGET_SERVERNAME: prometheus-telemeter.telemeter-stage.svc
